language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - oraclejdk11

addons:
  apt:
    packages:
    - sed

before_script:
  - mkdir output
  - mv conf/hl.config-travis conf/hl.config
  - sed -i -e "s/SUB_databaseUrl/${databaseUrl//\//\\/}/g" conf/hl.config
  - sed -i -e "s/SUB_databaseName/${databaseName//\//\\/}/g" conf/hl.config
  - sed -i -e "s/SUB_databaseUsername/${databaseUsername//\//\\/}/g" conf/hl.config
  - sed -i -e "s/SUB_databasePassword/${databasePassword//\//\\/}/g" conf/hl.config
  - mkdir models
  - curl -L -o glove.zip http://nlp.stanford.edu/data/glove.6B.zip
  - unzip glove.zip -d models/glove
  - mv models/glove/glove.6B.300d.txt models/glove/glove.model

script: mvn clean install
